<a href="https://colab.research.google.com/github/prinshu756/Exoplanet-detection/blob/main/notebooks/02_Light_Curve_Acquisition_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## This is the second notebook

In [1]:
!pip -q install lightkurve astropy astroquery pyarrow tqdm wotan

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 261.1/261.1 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 61.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 54.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.9/203.9 kB 14.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.4/15.4 MB 57.0 MB/s eta 0:00:00
  Building wheel for fbpca (setup.py) ... done
  Building wheel for memoization (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 4.0.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2026.6.0 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2026.6.0 which is incompatible.

In [2]:
import os
import gc
import time
import logging
import warnings

from pathlib import Path

import numpy as np
import pandas as pd

from tqdm.notebook import tqdm

import matplotlib.pyplot as plt

import lightkurve as lk

warnings.filterwarnings("ignore")

print("Libraries Imported Successfully")

Libraries Imported Successfully

/usr/local/lib/python3.12/dist-packages/lightkurve/prf/__init__.py:7: UserWarning: Warning: the tpfmodel submodule is not available without oktopus installed, which requires a current version of autograd. See #1452 for details.
  warnings.warn(

In [5]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
PROJECT_NAME = "AI_Exoplanet_Detection"

ROOT_DIR = Path("/content/drive/MyDrive") / PROJECT_NAME

CATALOG_DIR = ROOT_DIR / "data" / "processed"

LIGHTCURVE_DIR = ROOT_DIR / "data" / "raw" / "lightcurves"

LOG_DIR = ROOT_DIR / "logs"

MAX_TARGETS = 100      # None → Entire Catalog

MISSION = "TESS"

AUTHOR = "SPOC"

DOWNLOAD_TIMEOUT = 120

print("Configuration Loaded")

Configuration Loaded

In [7]:
LOG_FILE = LOG_DIR / "notebook_02.log"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler()
    ],
    force=True
)

logger = logging.getLogger("Notebook02")

logger.info("Notebook 02 Started")

2026-07-21 21:29:17,811 | INFO | Notebook 02 Started

In [9]:
catalog = pd.read_parquet(
    CATALOG_DIR / "master_catalog.parquet"
)

if MAX_TARGETS is not None:
    catalog = catalog.head(MAX_TARGETS)

print(f"Targets Loaded : {len(catalog):,}")

catalog.head()

Targets Loaded : 100

,tic_id,planet_name,host_star,ra,dec,orbital_period_days,planet_radius_earth,planet_mass_earth,stellar_teff,stellar_radius,stellar_mass,distance_pc,discovery_year,class_label,class_id,source_catalog
0,158722002,Kepler-1597 b,Kepler-1597,288.163969,42.481012,2.946542,1.06,1.20,6377.0,1.390,1.250,1221.050,2016,Planet,0,NASA Exoplanet Archive
1,121988890,Kepler-687 b,Kepler-687,289.315458,39.153291,20.505870,3.52,12.20,4841.0,0.730,0.770,633.660,2016,Planet,0,NASA Exoplanet Archive
2,350813882,Kepler-1596 b,Kepler-1596,285.557507,49.330087,66.373379,1.90,4.27,5706.0,0.920,0.950,2146.230,2016,Planet,0,NASA Exoplanet Archive
3,138728891,Kepler-692 b,Kepler-692,294.776807,40.153703,21.812935,3.11,9.85,5440.0,0.860,0.900,991.336,2016,Planet,0,NASA Exoplanet Archive
4,121598758,Kepler-150 c,Kepler-150,288.234103,40.520897,7.381998,3.69,13.20,5560.0,0.939,0.956,891.092,2014,Planet,0,NASA Exoplanet Archive

In [10]:
def output_file(tic_id, sector):

    return LIGHTCURVE_DIR / f"TIC_{tic_id}_Sector_{sector}.parquet"


def already_downloaded(tic_id, sector):

    return output_file(tic_id, sector).exists()


def save_lightcurve(df, tic_id, sector):

    df.to_parquet(
        output_file(tic_id, sector),
        index=False
    )

In [11]:
def search_lightcurve(tic_id):

    target = f"TIC {tic_id}"

    result = lk.search_lightcurve(
        target,
        mission=MISSION,
        author=AUTHOR
    )

    return result

In [12]:
def download_lightcurve(search_result):

    if len(search_result) == 0:
        return None

    lc = search_result.download()

    return lc

In [15]:
def lc_to_dataframe(lc, tic_id):

    # Extract metadata safely
    sector = lc.meta.get("SECTOR", np.nan)
    author = lc.meta.get("AUTHOR", "Unknown")
    mission = lc.meta.get("MISSION", "TESS")
    target_name = lc.meta.get("TARGETID", f"TIC {tic_id}")
    cadence = lc.meta.get("EXPOSURE", np.nan)

    df = pd.DataFrame({

        "tic_id": tic_id,

        "sector": sector,

        "mission": mission,

        "author": author,

        "target_name": target_name,

        "cadence_sec": cadence,

        "time": lc.time.value,

        "flux": lc.flux.value,

        "flux_err": lc.flux_err.value,

        "quality": lc.quality

    })

    return df

In [17]:
download_log = []

for _, row in tqdm(catalog.iterrows(), total=len(catalog)):

    tic_id = row["tic_id"]

    try:

        search = search_lightcurve(tic_id)

        if len(search) == 0:

            download_log.append({

                "tic_id": tic_id,

                "status": "Not Found"

            })

            continue

        lc = download_lightcurve(search)

        sector = lc.meta.get("SECTOR", "Unknown")

        if already_downloaded(tic_id, sector):

            download_log.append({

                "tic_id": tic_id,

                "status": "Skipped"

            })

            continue

        df = lc_to_dataframe(lc, tic_id)

        save_lightcurve(df, tic_id, sector)

        download_log.append({

            "tic_id": tic_id,

            "status": "Success",

            "sector": sector,

            "points": len(df)

        })

        del lc
        del df

        gc.collect()

    except Exception as e:

        logger.error(f"{tic_id} : {e}")

        download_log.append({

            "tic_id": tic_id,

            "status": "Failed",

            "error": str(e)

        })

  0%|          | 0/100 [00:00<?, ?it/s]

0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:42,412 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:42,674 | ERROR | 158722002 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (41/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:42,924 | INFO | 0% (41/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:43,114 | ERROR | 121988890 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (41/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:43,466 | INFO | 0% (41/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:43,761 | ERROR | 350813882 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (41/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:44,144 | INFO | 0% (41/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:44,355 | ERROR | 121598758 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:44,831 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:44,954 | ERROR | 123499226 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (23/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:45,082 | INFO | 0% (23/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:45,201 | ERROR | 184298883 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (52/18462) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:45,488 | INFO | 0% (52/18462) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:45,641 | ERROR | 271959909 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:46,024 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:46,129 | ERROR | 239229224 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:46,275 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:46,379 | ERROR | 170647523 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (33/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:46,525 | INFO | 0% (33/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:46,625 | ERROR | 271767300 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:46,763 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:46,860 | ERROR | 272845785 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (32/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:47,014 | INFO | 0% (32/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:47,135 | ERROR | 123496782 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:47,274 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:47,356 | ERROR | 122442334 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (132/112879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:47,606 | INFO | 0% (132/112879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:48,057 | ERROR | 63293562 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (26/18348) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:48,503 | INFO | 0% (26/18348) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:48,602 | ERROR | 269357457 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (53/18462) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:48,746 | INFO | 0% (53/18462) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:48,835 | ERROR | 272080244 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (23/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:48,978 | INFO | 0% (23/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:49,061 | ERROR | 122515955 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (42/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:49,455 | INFO | 0% (42/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:49,655 | ERROR | 158494681 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:49,741 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:49,790 | ERROR | 268704766 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:49,874 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:49,923 | ERROR | 137211068 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,007 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,062 | ERROR | 159175206 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,145 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,194 | ERROR | 273499989 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (41/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,294 | INFO | 0% (41/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,346 | ERROR | 121785939 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/19496) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,428 | INFO | 0% (22/19496) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,480 | ERROR | 121467823 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (26/18348) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,564 | INFO | 0% (26/18348) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,612 | ERROR | 27318774 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (23/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,696 | INFO | 0% (23/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,744 | ERROR | 184247532 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (23/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,830 | INFO | 0% (23/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,882 | ERROR | 137556197 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (33/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:50,966 | INFO | 0% (33/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,015 | ERROR | 121395761 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (33/17336) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,096 | INFO | 0% (33/17336) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,149 | ERROR | 120422519 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,232 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,297 | ERROR | 138805992 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (25/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,379 | INFO | 0% (25/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,429 | ERROR | 138213510 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (43/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,515 | INFO | 0% (43/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,564 | ERROR | 350810559 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (34/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,649 | INFO | 0% (34/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,703 | ERROR | 27011135 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,786 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,834 | ERROR | 27390527 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (52/18462) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,919 | INFO | 0% (52/18462) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:51,968 | ERROR | 272719153 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
1% (232/18654) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,050 | INFO | 1% (232/18654) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,098 | ERROR | 123447592 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,182 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,237 | ERROR | 159521326 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/19496) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,332 | INFO | 0% (22/19496) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,381 | ERROR | 164524311 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (52/18462) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,468 | INFO | 0% (52/18462) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,518 | ERROR | 270854411 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (43/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,602 | INFO | 0% (43/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,650 | ERROR | 279915745 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (34/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,737 | INFO | 0% (34/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,789 | ERROR | 243271716 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (30/18166) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,872 | INFO | 0% (30/18166) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:52,919 | ERROR | 158727691 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:53,003 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:53,058 | ERROR | 27843776 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (23/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:53,140 | INFO | 0% (23/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:53,190 | ERROR | 158434144 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (32/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:53,276 | INFO | 0% (32/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:53,332 | ERROR | 120252452 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (168/117871) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:53,492 | INFO | 0% (168/117871) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:53,710 | ERROR | 121603794 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:53,796 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:53,846 | ERROR | 138569175 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (23/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:53,933 | INFO | 0% (23/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:53,982 | ERROR | 270521167 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,067 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,116 | ERROR | 158923465 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (52/18462) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,200 | INFO | 0% (52/18462) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,251 | ERROR | 273582656 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
2% (308/17248) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,338 | INFO | 2% (308/17248) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,388 | ERROR | 164527695 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (32/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,481 | INFO | 0% (32/19643) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,531 | ERROR | 137558813 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
1% (231/18654) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,614 | INFO | 1% (231/18654) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,664 | ERROR | 230127302 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (52/18462) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,750 | INFO | 0% (52/18462) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,798 | ERROR | 138219758 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,883 | INFO | 0% (22/18810) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
2026-07-21 21:34:54,931 | ERROR | 270956861 : ('Byte-swapped arrays not supported', 'Conversion failed for column quality with type >i4')
0% (41/18597) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

In [18]:
report = pd.DataFrame(download_log)

report.to_csv(
    ROOT_DIR / "reports" / "download_report.csv",
    index=False
)

report.head()

      tic_id     status                                              error
0  158722002     Failed  ('Byte-swapped arrays not supported', 'Convers...
1  121988890     Failed  ('Byte-swapped arrays not supported', 'Convers...
2  350813882     Failed  ('Byte-swapped arrays not supported', 'Convers...
3  138728891  Not Found                                                NaN
4  121598758     Failed  ('Byte-swapped arrays not supported', 'Convers...